/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Mon Nov 14 14:37:06 2022
 * --------------------------------------------------------
 *
 */
#include "mbs_path.h"
#include "user_model.h"
#include "mbs_xml_binder_public.h"
#include "mbs_load_xml.h"
#include "useful_functions.h"
#include "mbs_message.h"
#include <math.h>
#include <float.h>

// ============================================================ //


UserModel* mbs_new_user_model() 
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));
    um->Wheels.F_Rad = 0.0;
    um->Wheels.R_Rad = 0.0;
    um->Wheels.Stiffness = 0.0;
 
    um->LeafSpring.k = 0.0;
    um->LeafSpring.l0 = 0.0;
    um->LeafSpring.k_stop = 0.0;
 
    um->Initial_State.FL_Wheel_Z = 0.0;
    um->Initial_State.RL_Wheel_Z = 0.0;
    um->Initial_State.FL_Wheel_F = 0.0;
    um->Initial_State.RL_Wheel_F = 0.0;
    um->Initial_State.FL_Leaf_F = 0.0;
    um->Initial_State.FL_Leaf_Z = 0.0;
    um->Initial_State.FL_Spring_F = 0.0;
    um->Initial_State.FL_Spring_Z = 0.0;
 
    um->Equilibrium_State.FR_Tyre = 0.0;
    um->Equilibrium_State.RR_Tyre = 0.0;
    um->Equilibrium_State.FR_Spring = 0.0;
    um->Equilibrium_State.RR_Spring = 0.0;
    um->Equilibrium_State.FR_Leaf_F = 0.0;
    um->Equilibrium_State.FR_Leaf_Rod_F = 0.0;
    um->Equilibrium_State.RR_Leaf_F = 0.0;
    um->Equilibrium_State.RR_Leaf_Rod_F = 0.0;
 
    um->Status.AntiPhase = 0;
    um->Status.Bump = 0;
    um->Status.Steering = 0;
    um->Status.Steering_sinus = 0;
    um->Status.Linear_Modal = 0;
 
    return um;
}

void mbs_delete_user_model(UserModel* um) 
{
    free(um);
}

 void mbs_load_user_model_xml(MbsInfos* mbs_infos, UserModel* um) 
{
    int ind_state_value = 1;

    um->Wheels.F_Rad = mbs_infos->user_models->user_model_list[0]->parameter_list[0]->value_list[1];
    um->Wheels.R_Rad = mbs_infos->user_models->user_model_list[0]->parameter_list[1]->value_list[1];
    um->Wheels.Stiffness = mbs_infos->user_models->user_model_list[0]->parameter_list[2]->value_list[1];
 
    um->LeafSpring.k = mbs_infos->user_models->user_model_list[1]->parameter_list[0]->value_list[1];
    um->LeafSpring.l0 = mbs_infos->user_models->user_model_list[1]->parameter_list[1]->value_list[1];
    um->LeafSpring.k_stop = mbs_infos->user_models->user_model_list[1]->parameter_list[2]->value_list[1];
 
    um->Initial_State.FL_Wheel_Z = mbs_infos->user_models->user_model_list[2]->parameter_list[0]->value_list[1];
    um->Initial_State.RL_Wheel_Z = mbs_infos->user_models->user_model_list[2]->parameter_list[1]->value_list[1];
    um->Initial_State.FL_Wheel_F = mbs_infos->user_models->user_model_list[2]->parameter_list[2]->value_list[1];
    um->Initial_State.RL_Wheel_F = mbs_infos->user_models->user_model_list[2]->parameter_list[3]->value_list[1];
    um->Initial_State.FL_Leaf_F = mbs_infos->user_models->user_model_list[2]->parameter_list[4]->value_list[1];
    um->Initial_State.FL_Leaf_Z = mbs_infos->user_models->user_model_list[2]->parameter_list[5]->value_list[1];
    um->Initial_State.FL_Spring_F = mbs_infos->user_models->user_model_list[2]->parameter_list[6]->value_list[1];
    um->Initial_State.FL_Spring_Z = mbs_infos->user_models->user_model_list[2]->parameter_list[7]->value_list[1];
 
    um->Equilibrium_State.FR_Tyre = mbs_infos->user_models->user_model_list[3]->parameter_list[0]->value_list[1];
    um->Equilibrium_State.RR_Tyre = mbs_infos->user_models->user_model_list[3]->parameter_list[1]->value_list[1];
    um->Equilibrium_State.FR_Spring = mbs_infos->user_models->user_model_list[3]->parameter_list[2]->value_list[1];
    um->Equilibrium_State.RR_Spring = mbs_infos->user_models->user_model_list[3]->parameter_list[3]->value_list[1];
    um->Equilibrium_State.FR_Leaf_F = mbs_infos->user_models->user_model_list[3]->parameter_list[4]->value_list[1];
    um->Equilibrium_State.FR_Leaf_Rod_F = mbs_infos->user_models->user_model_list[3]->parameter_list[5]->value_list[1];
    um->Equilibrium_State.RR_Leaf_F = mbs_infos->user_models->user_model_list[3]->parameter_list[6]->value_list[1];
    um->Equilibrium_State.RR_Leaf_Rod_F = mbs_infos->user_models->user_model_list[3]->parameter_list[7]->value_list[1];
 
    um->Status.AntiPhase = (int)lround(mbs_infos->user_models->user_model_list[4]->parameter_list[0]->value_list[1]);
    um->Status.Bump = (int)lround(mbs_infos->user_models->user_model_list[4]->parameter_list[1]->value_list[1]);
    um->Status.Steering = (int)lround(mbs_infos->user_models->user_model_list[4]->parameter_list[2]->value_list[1]);
    um->Status.Steering_sinus = (int)lround(mbs_infos->user_models->user_model_list[4]->parameter_list[3]->value_list[1]);
    um->Status.Linear_Modal = (int)lround(mbs_infos->user_models->user_model_list[4]->parameter_list[4]->value_list[1]);
 
}

 void mbs_bind_user_model(MbsInfos* mbs_infos, UserModel* um) 
{
    mbs_infos->user_models->user_model_list[0]->parameter_list[0]->val_ptr = &um->Wheels.F_Rad;
    mbs_infos->user_models->user_model_list[0]->parameter_list[1]->val_ptr = &um->Wheels.R_Rad;
    mbs_infos->user_models->user_model_list[0]->parameter_list[2]->val_ptr = &um->Wheels.Stiffness;
 
    mbs_infos->user_models->user_model_list[1]->parameter_list[0]->val_ptr = &um->LeafSpring.k;
    mbs_infos->user_models->user_model_list[1]->parameter_list[1]->val_ptr = &um->LeafSpring.l0;
    mbs_infos->user_models->user_model_list[1]->parameter_list[2]->val_ptr = &um->LeafSpring.k_stop;
 
    mbs_infos->user_models->user_model_list[2]->parameter_list[0]->val_ptr = &um->Initial_State.FL_Wheel_Z;
    mbs_infos->user_models->user_model_list[2]->parameter_list[1]->val_ptr = &um->Initial_State.RL_Wheel_Z;
    mbs_infos->user_models->user_model_list[2]->parameter_list[2]->val_ptr = &um->Initial_State.FL_Wheel_F;
    mbs_infos->user_models->user_model_list[2]->parameter_list[3]->val_ptr = &um->Initial_State.RL_Wheel_F;
    mbs_infos->user_models->user_model_list[2]->parameter_list[4]->val_ptr = &um->Initial_State.FL_Leaf_F;
    mbs_infos->user_models->user_model_list[2]->parameter_list[5]->val_ptr = &um->Initial_State.FL_Leaf_Z;
    mbs_infos->user_models->user_model_list[2]->parameter_list[6]->val_ptr = &um->Initial_State.FL_Spring_F;
    mbs_infos->user_models->user_model_list[2]->parameter_list[7]->val_ptr = &um->Initial_State.FL_Spring_Z;
 
    mbs_infos->user_models->user_model_list[3]->parameter_list[0]->val_ptr = &um->Equilibrium_State.FR_Tyre;
    mbs_infos->user_models->user_model_list[3]->parameter_list[1]->val_ptr = &um->Equilibrium_State.RR_Tyre;
    mbs_infos->user_models->user_model_list[3]->parameter_list[2]->val_ptr = &um->Equilibrium_State.FR_Spring;
    mbs_infos->user_models->user_model_list[3]->parameter_list[3]->val_ptr = &um->Equilibrium_State.RR_Spring;
    mbs_infos->user_models->user_model_list[3]->parameter_list[4]->val_ptr = &um->Equilibrium_State.FR_Leaf_F;
    mbs_infos->user_models->user_model_list[3]->parameter_list[5]->val_ptr = &um->Equilibrium_State.FR_Leaf_Rod_F;
    mbs_infos->user_models->user_model_list[3]->parameter_list[6]->val_ptr = &um->Equilibrium_State.RR_Leaf_F;
    mbs_infos->user_models->user_model_list[3]->parameter_list[7]->val_ptr = &um->Equilibrium_State.RR_Leaf_Rod_F;
 
    mbs_infos->user_models->user_model_list[4]->parameter_list[0]->val_ptr = &um->Status.AntiPhase;
    mbs_infos->user_models->user_model_list[4]->parameter_list[1]->val_ptr = &um->Status.Bump;
    mbs_infos->user_models->user_model_list[4]->parameter_list[2]->val_ptr = &um->Status.Steering;
    mbs_infos->user_models->user_model_list[4]->parameter_list[3]->val_ptr = &um->Status.Steering_sinus;
    mbs_infos->user_models->user_model_list[4]->parameter_list[4]->val_ptr = &um->Status.Linear_Modal;
 
}
 
 void mbs_print_user_model(UserModel* um) 
{

    printf("user_model->Wheels.F_Rad=%f\n", um->Wheels.F_Rad);
    printf("user_model->Wheels.R_Rad=%f\n", um->Wheels.R_Rad);
    printf("user_model->Wheels.Stiffness=%f\n", um->Wheels.Stiffness);
 
    printf("user_model->LeafSpring.k=%f\n", um->LeafSpring.k);
    printf("user_model->LeafSpring.l0=%f\n", um->LeafSpring.l0);
    printf("user_model->LeafSpring.k_stop=%f\n", um->LeafSpring.k_stop);
 
    printf("user_model->Initial_State.FL_Wheel_Z=%f\n", um->Initial_State.FL_Wheel_Z);
    printf("user_model->Initial_State.RL_Wheel_Z=%f\n", um->Initial_State.RL_Wheel_Z);
    printf("user_model->Initial_State.FL_Wheel_F=%f\n", um->Initial_State.FL_Wheel_F);
    printf("user_model->Initial_State.RL_Wheel_F=%f\n", um->Initial_State.RL_Wheel_F);
    printf("user_model->Initial_State.FL_Leaf_F=%f\n", um->Initial_State.FL_Leaf_F);
    printf("user_model->Initial_State.FL_Leaf_Z=%f\n", um->Initial_State.FL_Leaf_Z);
    printf("user_model->Initial_State.FL_Spring_F=%f\n", um->Initial_State.FL_Spring_F);
    printf("user_model->Initial_State.FL_Spring_Z=%f\n", um->Initial_State.FL_Spring_Z);
 
    printf("user_model->Equilibrium_State.FR_Tyre=%f\n", um->Equilibrium_State.FR_Tyre);
    printf("user_model->Equilibrium_State.RR_Tyre=%f\n", um->Equilibrium_State.RR_Tyre);
    printf("user_model->Equilibrium_State.FR_Spring=%f\n", um->Equilibrium_State.FR_Spring);
    printf("user_model->Equilibrium_State.RR_Spring=%f\n", um->Equilibrium_State.RR_Spring);
    printf("user_model->Equilibrium_State.FR_Leaf_F=%f\n", um->Equilibrium_State.FR_Leaf_F);
    printf("user_model->Equilibrium_State.FR_Leaf_Rod_F=%f\n", um->Equilibrium_State.FR_Leaf_Rod_F);
    printf("user_model->Equilibrium_State.RR_Leaf_F=%f\n", um->Equilibrium_State.RR_Leaf_F);
    printf("user_model->Equilibrium_State.RR_Leaf_Rod_F=%f\n", um->Equilibrium_State.RR_Leaf_Rod_F);
 
    printf("user_model->Status.AntiPhase=%d\n", um->Status.AntiPhase);
    printf("user_model->Status.Bump=%d\n", um->Status.Bump);
    printf("user_model->Status.Steering=%d\n", um->Status.Steering);
    printf("user_model->Status.Steering_sinus=%d\n", um->Status.Steering_sinus);
    printf("user_model->Status.Linear_Modal=%d\n", um->Status.Linear_Modal);
 
}
 
void mbs_get_user_model_size(int *n_user_model) 
{
    *n_user_model  = 5; 
}
 
void mbs_get_user_model_list(int *user_model_list) 
{
    user_model_list[1]  = 3; 
    user_model_list[2]  = 3; 
    user_model_list[3]  = 8; 
    user_model_list[4]  = 8; 
    user_model_list[5]  = 5; 

}

void mbs_save_um(FILE* stream, UserModel* um)
{
    if (isnan(um->Wheels.F_Rad)) { fprintf(stream, "         s->user_model->Wheels.F_Rad = NAN; \n");}
    else if (isinf(um->Wheels.F_Rad)) { fprintf(stream, "        s->user_model->Wheels.F_Rad = %d * INFINITY; \n", isinf(um->Wheels.F_Rad));}
    else { fprintf(stream, "        s->user_model->Wheels.F_Rad = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Wheels.F_Rad);}
    if (isnan(um->Wheels.R_Rad)) { fprintf(stream, "         s->user_model->Wheels.R_Rad = NAN; \n");}
    else if (isinf(um->Wheels.R_Rad)) { fprintf(stream, "        s->user_model->Wheels.R_Rad = %d * INFINITY; \n", isinf(um->Wheels.R_Rad));}
    else { fprintf(stream, "        s->user_model->Wheels.R_Rad = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Wheels.R_Rad);}
    if (isnan(um->Wheels.Stiffness)) { fprintf(stream, "         s->user_model->Wheels.Stiffness = NAN; \n");}
    else if (isinf(um->Wheels.Stiffness)) { fprintf(stream, "        s->user_model->Wheels.Stiffness = %d * INFINITY; \n", isinf(um->Wheels.Stiffness));}
    else { fprintf(stream, "        s->user_model->Wheels.Stiffness = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Wheels.Stiffness);}
 
    if (isnan(um->LeafSpring.k)) { fprintf(stream, "         s->user_model->LeafSpring.k = NAN; \n");}
    else if (isinf(um->LeafSpring.k)) { fprintf(stream, "        s->user_model->LeafSpring.k = %d * INFINITY; \n", isinf(um->LeafSpring.k));}
    else { fprintf(stream, "        s->user_model->LeafSpring.k = %.*e;\n", DBL_DECIMAL_DIG - 1, um->LeafSpring.k);}
    if (isnan(um->LeafSpring.l0)) { fprintf(stream, "         s->user_model->LeafSpring.l0 = NAN; \n");}
    else if (isinf(um->LeafSpring.l0)) { fprintf(stream, "        s->user_model->LeafSpring.l0 = %d * INFINITY; \n", isinf(um->LeafSpring.l0));}
    else { fprintf(stream, "        s->user_model->LeafSpring.l0 = %.*e;\n", DBL_DECIMAL_DIG - 1, um->LeafSpring.l0);}
    if (isnan(um->LeafSpring.k_stop)) { fprintf(stream, "         s->user_model->LeafSpring.k_stop = NAN; \n");}
    else if (isinf(um->LeafSpring.k_stop)) { fprintf(stream, "        s->user_model->LeafSpring.k_stop = %d * INFINITY; \n", isinf(um->LeafSpring.k_stop));}
    else { fprintf(stream, "        s->user_model->LeafSpring.k_stop = %.*e;\n", DBL_DECIMAL_DIG - 1, um->LeafSpring.k_stop);}
 
    if (isnan(um->Initial_State.FL_Wheel_Z)) { fprintf(stream, "         s->user_model->Initial_State.FL_Wheel_Z = NAN; \n");}
    else if (isinf(um->Initial_State.FL_Wheel_Z)) { fprintf(stream, "        s->user_model->Initial_State.FL_Wheel_Z = %d * INFINITY; \n", isinf(um->Initial_State.FL_Wheel_Z));}
    else { fprintf(stream, "        s->user_model->Initial_State.FL_Wheel_Z = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.FL_Wheel_Z);}
    if (isnan(um->Initial_State.RL_Wheel_Z)) { fprintf(stream, "         s->user_model->Initial_State.RL_Wheel_Z = NAN; \n");}
    else if (isinf(um->Initial_State.RL_Wheel_Z)) { fprintf(stream, "        s->user_model->Initial_State.RL_Wheel_Z = %d * INFINITY; \n", isinf(um->Initial_State.RL_Wheel_Z));}
    else { fprintf(stream, "        s->user_model->Initial_State.RL_Wheel_Z = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.RL_Wheel_Z);}
    if (isnan(um->Initial_State.FL_Wheel_F)) { fprintf(stream, "         s->user_model->Initial_State.FL_Wheel_F = NAN; \n");}
    else if (isinf(um->Initial_State.FL_Wheel_F)) { fprintf(stream, "        s->user_model->Initial_State.FL_Wheel_F = %d * INFINITY; \n", isinf(um->Initial_State.FL_Wheel_F));}
    else { fprintf(stream, "        s->user_model->Initial_State.FL_Wheel_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.FL_Wheel_F);}
    if (isnan(um->Initial_State.RL_Wheel_F)) { fprintf(stream, "         s->user_model->Initial_State.RL_Wheel_F = NAN; \n");}
    else if (isinf(um->Initial_State.RL_Wheel_F)) { fprintf(stream, "        s->user_model->Initial_State.RL_Wheel_F = %d * INFINITY; \n", isinf(um->Initial_State.RL_Wheel_F));}
    else { fprintf(stream, "        s->user_model->Initial_State.RL_Wheel_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.RL_Wheel_F);}
    if (isnan(um->Initial_State.FL_Leaf_F)) { fprintf(stream, "         s->user_model->Initial_State.FL_Leaf_F = NAN; \n");}
    else if (isinf(um->Initial_State.FL_Leaf_F)) { fprintf(stream, "        s->user_model->Initial_State.FL_Leaf_F = %d * INFINITY; \n", isinf(um->Initial_State.FL_Leaf_F));}
    else { fprintf(stream, "        s->user_model->Initial_State.FL_Leaf_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.FL_Leaf_F);}
    if (isnan(um->Initial_State.FL_Leaf_Z)) { fprintf(stream, "         s->user_model->Initial_State.FL_Leaf_Z = NAN; \n");}
    else if (isinf(um->Initial_State.FL_Leaf_Z)) { fprintf(stream, "        s->user_model->Initial_State.FL_Leaf_Z = %d * INFINITY; \n", isinf(um->Initial_State.FL_Leaf_Z));}
    else { fprintf(stream, "        s->user_model->Initial_State.FL_Leaf_Z = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.FL_Leaf_Z);}
    if (isnan(um->Initial_State.FL_Spring_F)) { fprintf(stream, "         s->user_model->Initial_State.FL_Spring_F = NAN; \n");}
    else if (isinf(um->Initial_State.FL_Spring_F)) { fprintf(stream, "        s->user_model->Initial_State.FL_Spring_F = %d * INFINITY; \n", isinf(um->Initial_State.FL_Spring_F));}
    else { fprintf(stream, "        s->user_model->Initial_State.FL_Spring_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.FL_Spring_F);}
    if (isnan(um->Initial_State.FL_Spring_Z)) { fprintf(stream, "         s->user_model->Initial_State.FL_Spring_Z = NAN; \n");}
    else if (isinf(um->Initial_State.FL_Spring_Z)) { fprintf(stream, "        s->user_model->Initial_State.FL_Spring_Z = %d * INFINITY; \n", isinf(um->Initial_State.FL_Spring_Z));}
    else { fprintf(stream, "        s->user_model->Initial_State.FL_Spring_Z = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Initial_State.FL_Spring_Z);}
 
    if (isnan(um->Equilibrium_State.FR_Tyre)) { fprintf(stream, "         s->user_model->Equilibrium_State.FR_Tyre = NAN; \n");}
    else if (isinf(um->Equilibrium_State.FR_Tyre)) { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Tyre = %d * INFINITY; \n", isinf(um->Equilibrium_State.FR_Tyre));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Tyre = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.FR_Tyre);}
    if (isnan(um->Equilibrium_State.RR_Tyre)) { fprintf(stream, "         s->user_model->Equilibrium_State.RR_Tyre = NAN; \n");}
    else if (isinf(um->Equilibrium_State.RR_Tyre)) { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Tyre = %d * INFINITY; \n", isinf(um->Equilibrium_State.RR_Tyre));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Tyre = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.RR_Tyre);}
    if (isnan(um->Equilibrium_State.FR_Spring)) { fprintf(stream, "         s->user_model->Equilibrium_State.FR_Spring = NAN; \n");}
    else if (isinf(um->Equilibrium_State.FR_Spring)) { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Spring = %d * INFINITY; \n", isinf(um->Equilibrium_State.FR_Spring));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Spring = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.FR_Spring);}
    if (isnan(um->Equilibrium_State.RR_Spring)) { fprintf(stream, "         s->user_model->Equilibrium_State.RR_Spring = NAN; \n");}
    else if (isinf(um->Equilibrium_State.RR_Spring)) { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Spring = %d * INFINITY; \n", isinf(um->Equilibrium_State.RR_Spring));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Spring = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.RR_Spring);}
    if (isnan(um->Equilibrium_State.FR_Leaf_F)) { fprintf(stream, "         s->user_model->Equilibrium_State.FR_Leaf_F = NAN; \n");}
    else if (isinf(um->Equilibrium_State.FR_Leaf_F)) { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Leaf_F = %d * INFINITY; \n", isinf(um->Equilibrium_State.FR_Leaf_F));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Leaf_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.FR_Leaf_F);}
    if (isnan(um->Equilibrium_State.FR_Leaf_Rod_F)) { fprintf(stream, "         s->user_model->Equilibrium_State.FR_Leaf_Rod_F = NAN; \n");}
    else if (isinf(um->Equilibrium_State.FR_Leaf_Rod_F)) { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Leaf_Rod_F = %d * INFINITY; \n", isinf(um->Equilibrium_State.FR_Leaf_Rod_F));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.FR_Leaf_Rod_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.FR_Leaf_Rod_F);}
    if (isnan(um->Equilibrium_State.RR_Leaf_F)) { fprintf(stream, "         s->user_model->Equilibrium_State.RR_Leaf_F = NAN; \n");}
    else if (isinf(um->Equilibrium_State.RR_Leaf_F)) { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Leaf_F = %d * INFINITY; \n", isinf(um->Equilibrium_State.RR_Leaf_F));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Leaf_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.RR_Leaf_F);}
    if (isnan(um->Equilibrium_State.RR_Leaf_Rod_F)) { fprintf(stream, "         s->user_model->Equilibrium_State.RR_Leaf_Rod_F = NAN; \n");}
    else if (isinf(um->Equilibrium_State.RR_Leaf_Rod_F)) { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Leaf_Rod_F = %d * INFINITY; \n", isinf(um->Equilibrium_State.RR_Leaf_Rod_F));}
    else { fprintf(stream, "        s->user_model->Equilibrium_State.RR_Leaf_Rod_F = %.*e;\n", DBL_DECIMAL_DIG - 1, um->Equilibrium_State.RR_Leaf_Rod_F);}
 
    fprintf(stream, "        s->user_model->Status.AntiPhase=%d;\n", um->Status.AntiPhase);
    fprintf(stream, "        s->user_model->Status.Bump=%d;\n", um->Status.Bump);
    fprintf(stream, "        s->user_model->Status.Steering=%d;\n", um->Status.Steering);
    fprintf(stream, "        s->user_model->Status.Steering_sinus=%d;\n", um->Status.Steering_sinus);
    fprintf(stream, "        s->user_model->Status.Linear_Modal=%d;\n", um->Status.Linear_Modal);
 
}

// ============================================================ //
 
