/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
<<<<<<< HEAD
 * Last update : Sun Jan  8 00:07:44 2023
=======
 * Last update : Sat Jan  7 15:49:09 2023
>>>>>>> 9cda43ee1ecf2f0d9951ae98a5b324420acf02bd
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define X_Chassis_id 1
#define Y_Chassis_id 2
#define Z_Chassis_id 3
#define Pitch_Chassis_id 4
#define Roll_Chassis_id 5
#define Yaw_Chassis_id 6
#define R1_FL_id 7
#define FL_Joint_7_id 8
#define FL_Joint_8_id 9
#define FL_Joint_9_id 10
#define R1_FL_Carrier_id 11
#define J_FL_Wheel_id 12
#define T2_Steering_Rack_id 13
#define R1_FR_id 14
#define T2_FR_Leaf_rod_id 15
#define T3_FR_Leaf_rod_id 16
#define FR_Joint_7_id 17
#define FR_Joint_8_id 18
#define FR_Joint_9_id 19
#define R1_FR_Carrier_id 20
#define J_FR_Wheel_id 21
#define R1_RR_id 22
#define T2_RR_Leaf_rod_id 23
#define T3_RR_Leaf_rod_id 24
#define RFR_Joint_7_id 25
#define RFR_Joint_8_id 26
#define RFR_Joint_9_id 27
#define R1_RR_Carrier_id 28
#define J_RR_Wheel_id 29
#define RFL_Joint_12_id 30
#define R1_RL_id 31
#define RFL_Joint_7_id 32
#define RFL_Joint_8_id 33
#define RFL_Joint_9_id 34
#define R1_RL_Carrier_id 35
#define J_RL_Wheel_id 36
#define T2_FL_Stop_id 37
#define T2_FR_Stop_id 38
#define T2_RL_Stop_id 39
#define T2_RR_Stop_id 40
#define Joint_0_id 41


// body

#define FL_Chassis_id 6
#define FL_Leaf_spring_id 7
#define FL_Carrier1_id 8
#define FL_AArm_id 9
#define FL_Carrier2_id 10
#define FL_Carrier3_id 11
#define FL_Wheel_id 12
#define F_Rack_id 13
#define FR_Leaf_spring_id 16
#define FR_Carrier1_id 17
#define FR_AArm_id 18
#define FR_Carrier2_id 19
#define FR_Carrier3_id 20
#define FR_Wheel_id 21
#define RRR_Leaf_spring_id 24
#define RRR_Carrier1_id 25
#define RRR_AArm_id 26
#define RRR_Carrier2_id 27
#define RRR_Carrier3_id 28
#define RRR_Wheel_id 29
#define RR_Rack_id 30
#define RRL_Leaf_spring_id 31
#define RRL_Carrier1_id 32
#define RRL_AArm_id 33
#define RRL_Carrier2_id 34
#define RRL_Carrier3_id 35
#define RRL_Wheel_id 36
#define FL_Stop_id 37
#define FR_Stop_id 38
#define RL_Stop_id 39
#define RR_Stop_id 40
#define Conducteur_id 41


// point

#define FL_Chassis_FL_AArm_attachement_id 1
#define FL_Chassis_FL_Leaf_spring_attachment_id 2
#define FL_Chassis_FL_Rack_center_point_id 3
#define FL_Chassis_FR_Leaf_spring_attachment_id 4
#define FL_Chassis_FR_AArm_attachement_id 5
#define FL_Chassis_RRR_AArm_attachement_id 6
#define FL_Chassis_RRR_Leaf_spring_attachment_id 7
#define FL_Chassis_RRL_Rack_center_point_id 8
#define FL_Chassis_RRL_AArm_attachement_id 9
#define FL_Chassis_RRL_Leaf_spring_attachment_id 10
#define FL_Chassis_FL_Bumper_id 11
#define FL_Chassis_FR_Bumper_id 12
#define FL_Chassis_RL_Bumper_id 13
#define FL_Chassis_RR_Bumper_id 14
#define FL_Chassis_F_Leaf_id 15
#define FL_Chassis_R_Leaf_id 16
#define FL_Chassis_Conducteur_id 17
#define FL_Leaf_spring_LeafSpringLength_id 18
#define FL_Carrier1_AArm_attachement_carrier1_id 19
#define FL_Carrier1_Wheel_carrier2_attachement_id 20
#define FL_AArm_AArm_length_id 21
#define FL_AArm_Point_0_id 22
#define FL_Carrier2_Carrier2_Carrier3_id 23
#define FL_Carrier2_C3_Cut_id 24
#define FL_Carrier3_Wheel_spin_point_id 25
//#define FL_Wheel_origin_id 26
#define F_Rack_Point_0_id 27
#define F_Rack_Point_1_id 28
#define FR_Leaf_spring_LeafSpringLength_id 29
#define FR_Carrier1_AArm_attachement_carrier1_id 30
#define FR_Carrier1_Wheel_carrier2_attachement_id 31
#define FR_AArm_AArm_length_id 32
#define FR_AArm_Point_0_id 33
#define FR_Carrier2_Carrier2_Carrier3_id 34
#define FR_Carrier2_C3_Cut_id 35
#define FR_Carrier3_Wheel_spin_point_id 36
//#define FR_Wheel_origin_id 37
#define RRR_Leaf_spring_LeafSpringLength_id 38
#define RRR_Carrier1_AArm_attachement_carrier1_id 39
#define RRR_Carrier1_Wheel_carrier2_attachement_id 40
#define RRR_AArm_AArm_length_id 41
#define RRR_AArm_Point_0_id 42
#define RRR_Carrier2_Carrier2_Carrier3_id 43
#define RRR_Carrier2_C3_Cut_id 44
#define RRR_Carrier3_Wheel_spin_point_id 45
//#define RRR_Wheel_origin_id 46
#define RR_Rack_Point_0_id 47
#define RR_Rack_Point_1_id 48
#define RRL_Leaf_spring_LeafSpringLength_id 49
#define RRL_Carrier1_AArm_attachement_carrier1_id 50
#define RRL_Carrier1_Wheel_carrier2_attachement_id 51
#define RRL_AArm_AArm_length_id 52
#define RRL_AArm_Point_0_id 53
#define RRL_Carrier2_Carrier2_Carrier3_id 54
#define RRL_Carrier2_C3_Cut_id 55
#define RRL_Carrier3_Wheel_spin_point_id 56
//#define RRL_Wheel_origin_id 57
//#define Conducteur_origin_id 58


// sensor

#define Sensor_Conducteur_id 1


// extforce

#define FL_Ground_id 1
#define FR_Ground_id 2
#define RR_Ground_id 3
#define RL_Ground_id 4


// links

#define FL_Bumper_id 1
#define RL_Bumper_id 2
#define FR_Bumper_id 3
#define RR_Bumper_id 4
#define FL_Leaf_id 5
#define FR_Leaf_id 6
#define RL_Leaf_id 7
#define RR_Leaf_id 8


// links 3D



// Rods

#define FL_Steering_bar_id 1
#define FR_Steering_bar_id 2
#define RRL_Steering_bar_id 3
#define RRR_Steering_bar_id 4


// ============================================================ //

# endif
