/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun Jan  8 23:07:19 2023
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 1260
#define M_9 6
#define M_12 57.35
#define M_18 6
#define M_21 57.35
#define M_26 6
#define M_29 57.35
#define M_33 6
#define M_36 57.35
#define M_41 70

// center of mass
#define L_2_9 0.16073
#define L_2_18 -0.16073
#define L_2_26 -0.16073
#define L_2_33 0.16073

// inertia
#define IN_1_6 130
#define IN_5_6 1620
#define IN_9_6 1670
#define IN_1_9 0.052099
#define IN_5_9 0.023235
#define IN_9_9 0.068864
#define IN_1_12 1.2402
#define IN_5_12 1.908
#define IN_9_12 1.2402
#define IN_1_18 0.052099
#define IN_5_18 0.023235
#define IN_9_18 0.068864
#define IN_1_21 1.2402
#define IN_5_21 1.908
#define IN_9_21 1.2402
#define IN_1_26 0.052099
#define IN_5_26 0.023235
#define IN_9_26 0.068864
#define IN_1_29 1.2402
#define IN_5_29 1.908
#define IN_9_29 1.2402
#define IN_1_33 0.052099
#define IN_5_33 0.023235
#define IN_9_33 0.068864
#define IN_1_36 1.2402
#define IN_5_36 1.908
#define IN_9_36 1.2402
#define IN_1_41 9.858
#define IN_5_41 11.258
#define IN_9_41 6.183

// body point
#define DPT_1_1 0.97
#define DPT_2_1 -0.259
#define DPT_3_1 -0.268
#define DPT_1_2 0.97
#define DPT_2_2 -0.1585
#define DPT_3_2 0.03
#define DPT_1_3 0.83
#define DPT_3_3 0.03
#define DPT_1_4 0.97
#define DPT_2_4 0.1585
#define DPT_3_4 0.03
#define DPT_1_5 0.97
#define DPT_2_5 0.259
#define DPT_3_5 -0.268
#define DPT_1_6 -1.047
#define DPT_2_6 0.259
#define DPT_3_6 -0.268
#define DPT_1_7 -1.047
#define DPT_2_7 0.1585
#define DPT_3_7 0.03
#define DPT_1_8 -0.907
#define DPT_3_8 0.03
#define DPT_1_9 -1.047
#define DPT_2_9 -0.259
#define DPT_3_9 -0.268
#define DPT_1_10 -1.047
#define DPT_2_10 -0.1585
#define DPT_3_10 0.03
#define DPT_1_11 1.045
#define DPT_2_11 -0.297
#define DPT_3_11 0.062
#define DPT_1_12 1.045
#define DPT_2_12 0.297
#define DPT_3_12 0.062
#define DPT_1_13 -1.122
#define DPT_2_13 -0.297
#define DPT_3_13 0.062
#define DPT_1_14 -1.122
#define DPT_2_14 0.297
#define DPT_3_14 0.062
#define DPT_1_15 0.97
#define DPT_3_15 0.137
#define DPT_1_16 -1.047
#define DPT_3_16 0.137
#define DPT_2_17 0.259
#define DPT_3_17 0.43
#define DPT_2_18 -0.336647
#define DPT_3_19 -0.313465
#define DPT_3_20 -0.181643
#define DPT_2_21 0.32146
#define DPT_1_22 0.075
#define DPT_2_22 0.0728438
#define DPT_3_22 -0.0046671
#define DPT_3_23 -0.131821
#define DPT_1_24 -0.14
#define DPT_2_24 0.0385371
#define DPT_3_24 0.192362
#define DPT_2_25 -0.043
#define DPT_3_25 0.127
#define DPT_2_27 -0.07
#define DPT_2_28 0.07
#define DPT_2_29 0.336647
#define DPT_3_30 -0.313465
#define DPT_3_31 -0.181643
#define DPT_2_32 -0.32146
#define DPT_1_33 0.075
#define DPT_2_33 -0.0728438
#define DPT_3_33 -0.0046671
#define DPT_3_34 -0.131821
#define DPT_1_35 -0.14
#define DPT_2_35 -0.0385371
#define DPT_3_35 0.192362
#define DPT_2_36 0.043
#define DPT_3_36 0.127
#define DPT_2_38 0.336647
#define DPT_3_39 -0.313465
#define DPT_3_40 -0.181643
#define DPT_2_41 -0.32146
#define DPT_1_42 -0.075
#define DPT_2_42 -0.0728438
#define DPT_3_42 -0.0046671
#define DPT_3_43 -0.131821
#define DPT_1_44 0.14
#define DPT_2_44 -0.0385371
#define DPT_3_44 0.192362
#define DPT_2_45 0.043
#define DPT_3_45 0.127
#define DPT_2_47 -0.07
#define DPT_2_48 0.07
#define DPT_2_49 -0.336647
#define DPT_3_50 -0.313465
#define DPT_3_51 -0.181643
#define DPT_2_52 0.32146
#define DPT_1_53 -0.075
#define DPT_2_53 0.0728438
#define DPT_3_53 -0.0046671
#define DPT_3_54 -0.131821
#define DPT_1_55 0.14
#define DPT_2_55 0.0385371
#define DPT_3_55 0.192362
#define DPT_2_56 -0.043
#define DPT_3_56 0.127

// ============================================================ //

# endif
